# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/input_reader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/input_reader.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x19protos/input_reader.proto\x12\x17object_detection.protos\"\xeb\x03\n\x0bInputReader\x12\x18\n\x0elabel_map_path\x18\x01 \x01(\t:\x00\x12\x15\n\x07shuffle\x18\x02 \x01(\x08:\x04true\x12\x1c\n\x0equeue_capacity\x18\x03 \x01(\r:\x04\x32\x30\x30\x30\x12\x1f\n\x11min_after_dequeue\x18\x04 \x01(\r:\x04\x31\x30\x30\x30\x12\x15\n\nnum_epochs\x18\x05 \x01(\r:\x01\x30\x12\x16\n\x0bnum_readers\x18\x06 \x01(\r:\x01\x38\x12\"\n\x13load_instance_masks\x18\x07 \x01(\x08:\x05\x66\x61lse\x12N\n\x16tf_record_input_reader\x18\x08 \x01(\x0b\x32,.object_detection.protos.TFRecordInputReaderH\x00\x12M\n\x15\x65xternal_input_reader\x18\t \x01(\x0b\x32,.object_detection.protos.ExternalInputReaderH\x00\x12\x1a\n\x0bimage_dtype\x18\n \x01(\t:\x05uint8\x12N\n\x18preprocess_input_options\x18\x0b \x03(\x0b\x32,.object_detection.protos.PreprocessInputStepB\x0e\n\x0cinput_reader\"+\n\x13TFRecordInputReader\x12\x14\n\ninput_path\x18\x01 \x01(\t:\x00\"\x1c\n\x13\x45xternalInputReader*\x05\x08\x01\x10\xe8\x07\"\xde\x02\n\x13PreprocessInputStep\x12W\n\x1bswap_height_width_of_rboxes\x18\x01 \x01(\x0b\x32\x30.object_detection.protos.SwapHeightWidthOfRBoxesH\x00\x12R\n\x18subtract_angle_of_rboxes\x18\x02 \x01(\x0b\x32..object_detection.protos.SubtractAngleOfRBoxesH\x00\x12@\n\x0enormalize_tiff\x18\x03 \x01(\x0b\x32&.object_detection.protos.NormalizeTIffH\x00\x12?\n\x0e\x63utoff_max_gts\x18\x04 \x01(\x0b\x32%.object_detection.protos.CutoffMaxGTsH\x00\x42\x17\n\x15preprocess_input_step\"\x19\n\x17SwapHeightWidthOfRBoxes\"&\n\x15SubtractAngleOfRBoxes\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\"\x0f\n\rNormalizeTIff\"$\n\x0c\x43utoffMaxGTs\x12\x14\n\x07max_gts\x18\x01 \x01(\r:\x03\x31\x30\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INPUTREADER = _descriptor.Descriptor(
  name='InputReader',
  full_name='object_detection.protos.InputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_map_path', full_name='object_detection.protos.InputReader.label_map_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shuffle', full_name='object_detection.protos.InputReader.shuffle', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queue_capacity', full_name='object_detection.protos.InputReader.queue_capacity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_after_dequeue', full_name='object_detection.protos.InputReader.min_after_dequeue', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_epochs', full_name='object_detection.protos.InputReader.num_epochs', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_readers', full_name='object_detection.protos.InputReader.num_readers', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_instance_masks', full_name='object_detection.protos.InputReader.load_instance_masks', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tf_record_input_reader', full_name='object_detection.protos.InputReader.tf_record_input_reader', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_input_reader', full_name='object_detection.protos.InputReader.external_input_reader', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_dtype', full_name='object_detection.protos.InputReader.image_dtype', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("uint8").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preprocess_input_options', full_name='object_detection.protos.InputReader.preprocess_input_options', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='input_reader', full_name='object_detection.protos.InputReader.input_reader',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=55,
  serialized_end=546,
)


_TFRECORDINPUTREADER = _descriptor.Descriptor(
  name='TFRecordInputReader',
  full_name='object_detection.protos.TFRecordInputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_path', full_name='object_detection.protos.TFRecordInputReader.input_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=591,
)


_EXTERNALINPUTREADER = _descriptor.Descriptor(
  name='ExternalInputReader',
  full_name='object_detection.protos.ExternalInputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1, 1000), ],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=621,
)


_PREPROCESSINPUTSTEP = _descriptor.Descriptor(
  name='PreprocessInputStep',
  full_name='object_detection.protos.PreprocessInputStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='swap_height_width_of_rboxes', full_name='object_detection.protos.PreprocessInputStep.swap_height_width_of_rboxes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtract_angle_of_rboxes', full_name='object_detection.protos.PreprocessInputStep.subtract_angle_of_rboxes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalize_tiff', full_name='object_detection.protos.PreprocessInputStep.normalize_tiff', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cutoff_max_gts', full_name='object_detection.protos.PreprocessInputStep.cutoff_max_gts', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='preprocess_input_step', full_name='object_detection.protos.PreprocessInputStep.preprocess_input_step',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=624,
  serialized_end=974,
)


_SWAPHEIGHTWIDTHOFRBOXES = _descriptor.Descriptor(
  name='SwapHeightWidthOfRBoxes',
  full_name='object_detection.protos.SwapHeightWidthOfRBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=976,
  serialized_end=1001,
)


_SUBTRACTANGLEOFRBOXES = _descriptor.Descriptor(
  name='SubtractAngleOfRBoxes',
  full_name='object_detection.protos.SubtractAngleOfRBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='object_detection.protos.SubtractAngleOfRBoxes.angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1003,
  serialized_end=1041,
)


_NORMALIZETIFF = _descriptor.Descriptor(
  name='NormalizeTIff',
  full_name='object_detection.protos.NormalizeTIff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1043,
  serialized_end=1058,
)


_CUTOFFMAXGTS = _descriptor.Descriptor(
  name='CutoffMaxGTs',
  full_name='object_detection.protos.CutoffMaxGTs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_gts', full_name='object_detection.protos.CutoffMaxGTs.max_gts', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1060,
  serialized_end=1096,
)

_INPUTREADER.fields_by_name['tf_record_input_reader'].message_type = _TFRECORDINPUTREADER
_INPUTREADER.fields_by_name['external_input_reader'].message_type = _EXTERNALINPUTREADER
_INPUTREADER.fields_by_name['preprocess_input_options'].message_type = _PREPROCESSINPUTSTEP
_INPUTREADER.oneofs_by_name['input_reader'].fields.append(
  _INPUTREADER.fields_by_name['tf_record_input_reader'])
_INPUTREADER.fields_by_name['tf_record_input_reader'].containing_oneof = _INPUTREADER.oneofs_by_name['input_reader']
_INPUTREADER.oneofs_by_name['input_reader'].fields.append(
  _INPUTREADER.fields_by_name['external_input_reader'])
_INPUTREADER.fields_by_name['external_input_reader'].containing_oneof = _INPUTREADER.oneofs_by_name['input_reader']
_PREPROCESSINPUTSTEP.fields_by_name['swap_height_width_of_rboxes'].message_type = _SWAPHEIGHTWIDTHOFRBOXES
_PREPROCESSINPUTSTEP.fields_by_name['subtract_angle_of_rboxes'].message_type = _SUBTRACTANGLEOFRBOXES
_PREPROCESSINPUTSTEP.fields_by_name['normalize_tiff'].message_type = _NORMALIZETIFF
_PREPROCESSINPUTSTEP.fields_by_name['cutoff_max_gts'].message_type = _CUTOFFMAXGTS
_PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step'].fields.append(
  _PREPROCESSINPUTSTEP.fields_by_name['swap_height_width_of_rboxes'])
_PREPROCESSINPUTSTEP.fields_by_name['swap_height_width_of_rboxes'].containing_oneof = _PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step']
_PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step'].fields.append(
  _PREPROCESSINPUTSTEP.fields_by_name['subtract_angle_of_rboxes'])
_PREPROCESSINPUTSTEP.fields_by_name['subtract_angle_of_rboxes'].containing_oneof = _PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step']
_PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step'].fields.append(
  _PREPROCESSINPUTSTEP.fields_by_name['normalize_tiff'])
_PREPROCESSINPUTSTEP.fields_by_name['normalize_tiff'].containing_oneof = _PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step']
_PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step'].fields.append(
  _PREPROCESSINPUTSTEP.fields_by_name['cutoff_max_gts'])
_PREPROCESSINPUTSTEP.fields_by_name['cutoff_max_gts'].containing_oneof = _PREPROCESSINPUTSTEP.oneofs_by_name['preprocess_input_step']
DESCRIPTOR.message_types_by_name['InputReader'] = _INPUTREADER
DESCRIPTOR.message_types_by_name['TFRecordInputReader'] = _TFRECORDINPUTREADER
DESCRIPTOR.message_types_by_name['ExternalInputReader'] = _EXTERNALINPUTREADER
DESCRIPTOR.message_types_by_name['PreprocessInputStep'] = _PREPROCESSINPUTSTEP
DESCRIPTOR.message_types_by_name['SwapHeightWidthOfRBoxes'] = _SWAPHEIGHTWIDTHOFRBOXES
DESCRIPTOR.message_types_by_name['SubtractAngleOfRBoxes'] = _SUBTRACTANGLEOFRBOXES
DESCRIPTOR.message_types_by_name['NormalizeTIff'] = _NORMALIZETIFF
DESCRIPTOR.message_types_by_name['CutoffMaxGTs'] = _CUTOFFMAXGTS

InputReader = _reflection.GeneratedProtocolMessageType('InputReader', (_message.Message,), dict(
  DESCRIPTOR = _INPUTREADER,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.InputReader)
  ))
_sym_db.RegisterMessage(InputReader)

TFRecordInputReader = _reflection.GeneratedProtocolMessageType('TFRecordInputReader', (_message.Message,), dict(
  DESCRIPTOR = _TFRECORDINPUTREADER,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.TFRecordInputReader)
  ))
_sym_db.RegisterMessage(TFRecordInputReader)

ExternalInputReader = _reflection.GeneratedProtocolMessageType('ExternalInputReader', (_message.Message,), dict(
  DESCRIPTOR = _EXTERNALINPUTREADER,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.ExternalInputReader)
  ))
_sym_db.RegisterMessage(ExternalInputReader)

PreprocessInputStep = _reflection.GeneratedProtocolMessageType('PreprocessInputStep', (_message.Message,), dict(
  DESCRIPTOR = _PREPROCESSINPUTSTEP,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.PreprocessInputStep)
  ))
_sym_db.RegisterMessage(PreprocessInputStep)

SwapHeightWidthOfRBoxes = _reflection.GeneratedProtocolMessageType('SwapHeightWidthOfRBoxes', (_message.Message,), dict(
  DESCRIPTOR = _SWAPHEIGHTWIDTHOFRBOXES,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.SwapHeightWidthOfRBoxes)
  ))
_sym_db.RegisterMessage(SwapHeightWidthOfRBoxes)

SubtractAngleOfRBoxes = _reflection.GeneratedProtocolMessageType('SubtractAngleOfRBoxes', (_message.Message,), dict(
  DESCRIPTOR = _SUBTRACTANGLEOFRBOXES,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.SubtractAngleOfRBoxes)
  ))
_sym_db.RegisterMessage(SubtractAngleOfRBoxes)

NormalizeTIff = _reflection.GeneratedProtocolMessageType('NormalizeTIff', (_message.Message,), dict(
  DESCRIPTOR = _NORMALIZETIFF,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.NormalizeTIff)
  ))
_sym_db.RegisterMessage(NormalizeTIff)

CutoffMaxGTs = _reflection.GeneratedProtocolMessageType('CutoffMaxGTs', (_message.Message,), dict(
  DESCRIPTOR = _CUTOFFMAXGTS,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.CutoffMaxGTs)
  ))
_sym_db.RegisterMessage(CutoffMaxGTs)


# @@protoc_insertion_point(module_scope)
